server:
  port: 8082
spring:
  rabbitmq:
    request:
      host: localhost
      port: 5672
      username: guest
      password: guest
      exchange:
        # Nome da exchange
        producer: ex.producer.aula-spring
      routing-key:
        # Nome da fila queue (rk = router key - poderia ser queue tb)
        producer: rk.producer.aula-spring
      # Controle de erros: Caso a mensagem seja recebida pelo consumer com erro ela vai cair novamente na queue para que não seja perdida.
      deadletter:
        # Nome da deadletter
        producer: dl.producer.aula-spring

